### ISSUE TITLE
Don't support node v6.2.1

### ISSUE THREAD

**Issue by mebiusashan** [astro/node-expat#158]
if i want to use it on node v6.2.1,wen i install it , well look some error info.like this:

`> node-expat@2.3.15 install /home/nodeserver/xmltool/myapp/node_modules/node-expat
> node-gyp rebuild

make: Entering directory `/home/nodeserver/xmltool/myapp/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
In file included from ../node-expat.cc:1:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /root/.node-gyp/6.2.1/include/node/node.h:42,
                 from ../../nan/nan.h:47,
                 from ../node-expat.cc:1:
/root/.node-gyp/6.2.1/include/node/v8.h:341: error: expected unqualified-id before 'using'
/root/.node-gyp/6.2.1/include/node/v8.h: In constructor 'v8::MaybeLocal<T>::MaybeLocal()':
/root/.node-gyp/6.2.1/include/node/v8.h:358: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h: In member function 'bool v8::MaybeLocal<T>::IsEmpty() const':
/root/.node-gyp/6.2.1/include/node/v8.h:365: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h: In member function 'bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const':
/root/.node-gyp/6.2.1/include/node/v8.h:369: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h: In member function 'bool v8::WeakCallbackInfo<T>::IsFirstPass() const':
/root/.node-gyp/6.2.1/include/node/v8.h:437: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h: At global scope:
/root/.node-gyp/6.2.1/include/node/v8.h:477: error: expected unqualified-id before 'using'
/root/.node-gyp/6.2.1/include/node/v8.h: In constructor 'v8::Global<T>::Global()':
/root/.node-gyp/6.2.1/include/node/v8.h:809: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h: In constructor 'v8::Global<T>::Global(v8::Global<T>&&)':
/root/.node-gyp/6.2.1/include/node/v8.h:834: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h: In member function 'v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)':
/root/.node-gyp/6.2.1/include/node/v8.h:846: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h: At global scope:
/root/.node-gyp/6.2.1/include/node/v8.h:871: error: expected unqualified-id before 'using'
/root/.node-gyp/6.2.1/include/node/v8.h:1108: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h:1114: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h: In member function 'v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const':
/root/.node-gyp/6.2.1/include/node/v8.h:3246: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h: At global scope:
/root/.node-gyp/6.2.1/include/node/v8.h:4463: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h:4479: error: 'nullptr' was not declared in this scope
/root/.node-gyp/6.2.1/include/node/v8.h: In member function 'v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()':
/root/.node-gyp/6.2.1/include/node/v8.h:7348: error: 'nullptr' was not declared in this scope
In file included from ../../nan/nan.h:190,
                 from ../node-expat.cc:1:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before 'using'
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before 'using'
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:31: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:36: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:41: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:46: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:51: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:59: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:64: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:69: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:76: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:83: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:91: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:98: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:108: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:114: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:118: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:125: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:130: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:135: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:139: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:145: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:150: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:156: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:162: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:168: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:174: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:180: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:186: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:194: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:201: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:205: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:209: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:213: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:217: error: expected initializer before '<' token
../node-expat.cc:498: error: expected '}' at end of input
../../nan/nan_callbacks_12_inl.h:167: warning: 'void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:181: warning: 'void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:197: warning: 'void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:253: warning: 'void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:270: warning: 'void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:290: warning: 'void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:306: warning: 'void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:323: warning: 'void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:428: warning: 'void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:444: warning: 'void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:464: warning: 'void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:480: warning: 'void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:496: warning: 'void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)' defined but not used
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
make: Leaving directory `/home/nodeserver/xmltool/myapp/node_modules/node-expat/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/soft/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-573.22.1.el6.x86_64
gyp ERR! command "/home/soft/node/bin/node" "/home/soft/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeserver/xmltool/myapp/node_modules/node-expat
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 2.6.32-573.22.1.el6.x86_64
npm ERR! argv "/home/soft/node/bin/node" "/home/soft/node/bin/npm" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nodeserver/xmltool/myapp/npm-debug.log`

**Comment by astro** [comment]
I'm using Debian where this node version is not yet available.

Does bumping the nan dependency solve the problem?

**Comment by carloscarvallo** [comment]
https://github.com/nodejs/node-gyp/issues/809
