### ISSUE TITLE
Issue Installing on Windows

### ISSUE THREAD

**Issue by michaelraypace** [astro/node-expat#166]
Over the past two day's I've had issues installing on multiple platforms. Here are the errors I"m seeing on Windows:

```
{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  xmlparse.c
  xmltok.c
  xmlrole.c
  win_delay_load_hook.c
..\..\..\deps\libexpat\lib\xmlparse.c(1844): warning C4244: 'return': conversion from '__int64' to 'XML_Index', possib le loss of data [c:\<redacted>\node_modules\node-expat\build\deps\libexpat\expat.vcxproj]
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNo tifyHook2': redefinition; different type modifiers [c:\<redacted>\node_modules\node-expat\build\deps\libexpat\expat. vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNo
  tifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\<redacted>\node_modules\node-expat
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN nodetest@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-S" "xml-object-stream"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\<redacted>\npm-debug.log
```

**Comment by mitulchauhan1** [comment]
I have faced this same issue but it get solved by following this steps by modifying package.json
[http://stackoverflow.com/questions/38149603/npm-install-fails-with-error-c2373-with-vs2015-update-3](url)

**Comment by astro** [comment]
We don't have `node-gyp` in our `package.json`.

If you have a working fix please submit a PR. I don't have access to a Windows machine for testing.

**Comment by rflpsz** [comment]
All the links with how to use this at Windows are broken. Are there some work link? Pls

**Comment by 0shape** [comment]
this help`s in most cases
npm install --global --production windows-build-tools

**Comment by helzgate** [comment]
@Oshape wow, that actually worked on Windows Server 2012, lol.  I just knew it wouldn't, but I was wrong!  This is regarding xml2json package that depends on this anyway.  I had to have an admin prompt for both installing the build tools, then installing the local package xml2json as well.

**Comment by froglander** [comment]
For the person who said the link someone posted was broken, I think this one works
https://stackoverflow.com/questions/38149603/npm-install-fails-with-error-c2373-with-vs2015-update-3

**Comment by UncleGus** [comment]
I have solved this. If you notice this part of the command `  else (node "" rebuild )` what I think is happening is that it is incorrectly evaluating `if not defined npm_config_node_gyp` as `false` and trying to run nothing instead of node-gyp. What you need to do is define your `npm_config_node_gyp` variable. You can do this like so:
`export npm_config_node_gyp=<PATH_TO_NODE_GYP_PACKAGE_FOLDER>` remember that Windows will need double backslashes. For me, it looked like this:
`export npm_config_node_gyp=C:\\Users\\781990\\AppData\\Roaming\\nvm\\v6.11.0\\node_modules\\node-gyp`

**Comment by ashjas** [comment]
> this help`s in most cases
> npm install --global --production windows-build-tools

This works wonderfully. Though it took >30 mins to install..
+ windows-build-tools@5.1.0
added 145 packages from 99 contributors in 1880.4s

**Comment by ogrotten** [comment]
@UncleGus `export` isn't recognized in windows powershell. Are you on mac/linux?
