### ISSUE TITLE
npm-expat fails compilation on Node 7

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [astro/node-expat#167]
Environment: 
  Node: v7.0.0-nightly20161017e6d1d54230
  OS: Ubuntu 14.04 x64
  User: root ( I Know, but stuck with this for now)

npm bugs node-expat gives me the following issue

0 verbose etag https://registry.npmjs.org/node-expat from cache
21 verbose get saving node-expat to /root/.npm/registry.npmjs.org/node-expat/.cache.json
22 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
23 silly bugs url https://github.com/astro/node-expat/issues
24 verbose stack Error: spawn xdg-open ENOENT
24 verbose stack     at exports._errnoException (util.js:1026:11)
24 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
24 verbose stack     at onErrorNT (internal/child_process.js:359:16)
24 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
24 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
25 verbose cwd /root/apps/es7
26 error Linux 3.13.0-37-generic
27 error argv "/root/.nvm/versions/node/v7.0.0-nightly20161017e6d1d54230/bin/node" "/root/.nvm/versions/node/v7.0.0-nightly20161017e6d1d54230/bin/npm" "bugs" "node-expat"
28 error node v7.0.0-nightly20161017e6d1d54230
29 error npm  v3.10.8
30 error path xdg-open
31 error code ENOENT
32 error errno ENOENT
33 error syscall spawn xdg-open
34 error enoent spawn xdg-open ENOENT
35 error enoent spawn xdg-open ENOENT
35 error enoent This is most likely not a problem with npm itself
35 error enoent and is related to npm not being able to find a file.
36 verbose exit [ 1, true ]

**Comment by parkerlreed** [comment]
And node 8

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@5.4.2
3 info using node@v8.6.0
4 verbose npm-session c8f14fd2297d14f0
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall nodecast@0.0.10
7 info lifecycle nodecast@0.0.10~preinstall: nodecast@0.0.10
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 http fetch GET 200 https://registry.npmjs.org/xml2json 14ms (from cache)
15 silly pacote range manifest for xml2json@^0.4.0 fetched in 28ms
16 http fetch GET 200 https://registry.npmjs.org/node-expat 2ms (from cache)
17 silly pacote version manifest for node-expat@2.1.4 fetched in 4ms
18 http fetch GET 304 https://registry.npmjs.org/nan 183ms (from cache)
19 silly pacote range manifest for nan@~0.6.0 fetched in 184ms
20 silly pacote range manifest for xml2json@^0.4.0 fetched in 2ms
21 silly resolveWithNewModule xml2json@0.4.0 checking installable status
22 silly pacote version manifest for node-expat@2.1.4 fetched in 1ms
23 silly resolveWithNewModule node-expat@2.1.4 checking installable status
24 silly pacote range manifest for nan@~0.6.0 fetched in 1ms
25 silly resolveWithNewModule nan@0.6.0 checking installable status
26 silly currentTree nodecast@0.0.10
26 silly currentTree ├── async@0.6.2
26 silly currentTree ├── balanced-match@1.0.0
26 silly currentTree ├── brace-expansion@1.1.8
26 silly currentTree ├── browser-stdout@1.3.0
26 silly currentTree ├── bunyan-prettystream@0.1.3
26 silly currentTree ├── bunyan@0.22.3
26 silly currentTree ├── commander@2.1.0
26 silly currentTree ├── concat-map@0.0.1
26 silly currentTree ├── cookiejar@1.3.0
26 silly currentTree ├── debug@0.7.4
26 silly currentTree ├── diff@3.3.1
26 silly currentTree ├── dtrace-provider@0.2.8
26 silly currentTree ├── emitter-component@1.0.0
26 silly currentTree ├── escape-string-regexp@1.0.5
26 silly currentTree ├── eslint-plugin-node@5.2.0
26 silly currentTree ├── extend@1.2.1
26 silly currentTree ├── formidable@1.0.14
26 silly currentTree ├── fs.realpath@1.0.0
26 silly currentTree ├── glob@6.0.4
26 silly currentTree ├── growl@1.10.2
26 silly currentTree ├── has-flag@2.0.0
26 silly currentTree ├── he@1.1.1
26 silly currentTree ├── ignore@3.3.5
26 silly currentTree ├── inflight@1.0.6
26 silly currentTree ├── inherits@2.0.3
26 silly currentTree ├── methods@0.0.1
26 silly currentTree ├── mime@1.2.5
26 silly currentTree ├── minimatch@3.0.4
26 silly currentTree ├── minimist@0.0.8
26 silly currentTree ├── mkdirp@0.5.1
26 silly currentTree ├─┬ mocha@4.0.0
26 silly currentTree │ ├── commander@2.11.0
26 silly currentTree │ ├── debug@3.1.0
26 silly currentTree │ └── glob@7.1.2
26 silly currentTree ├── ms@2.0.0
26 silly currentTree ├── mv@2.1.1
26 silly currentTree ├── nan@1.0.0
26 silly currentTree ├── ncp@2.0.0
26 silly currentTree ├── node-ssdp@0.2.2
26 silly currentTree ├── once@1.4.0
26 silly currentTree ├── optimist@0.6.1
26 silly currentTree ├── options@0.0.6
26 silly currentTree ├── path-is-absolute@1.0.1
26 silly currentTree ├── path-parse@1.0.5
26 silly currentTree ├── qs@0.6.5
26 silly currentTree ├── reduce-component@1.0.1
26 silly currentTree ├── require-dir@0.1.0
26 silly currentTree ├── resolve@1.4.0
26 silly currentTree ├── rimraf@2.4.5
26 silly currentTree ├── semver@5.3.0
26 silly currentTree ├── should-equal@2.0.0
26 silly currentTree ├── should-format@3.0.3
26 silly currentTree ├── should-type-adaptors@1.0.1
26 silly currentTree ├── should-type@1.4.0
26 silly currentTree ├── should-util@1.0.0
26 silly currentTree ├── should@13.1.0
26 silly currentTree ├── superagent@0.17.0
26 silly currentTree ├── supports-color@4.4.0
26 silly currentTree ├── tinycolor@0.0.1
26 silly currentTree ├── to-array@0.1.4
26 silly currentTree ├── url-join@0.0.1
26 silly currentTree ├── wordwrap@0.0.3
26 silly currentTree ├── wrappy@1.0.2
26 silly currentTree └── ws@0.4.32
27 silly idealTree nodecast@0.0.10
27 silly idealTree ├── async@0.6.2
27 silly idealTree ├── balanced-match@1.0.0
27 silly idealTree ├── brace-expansion@1.1.8
27 silly idealTree ├── browser-stdout@1.3.0
27 silly idealTree ├── bunyan-prettystream@0.1.3
27 silly idealTree ├── bunyan@0.22.3
27 silly idealTree ├── commander@2.1.0
27 silly idealTree ├── concat-map@0.0.1
27 silly idealTree ├── cookiejar@1.3.0
27 silly idealTree ├── debug@0.7.4
27 silly idealTree ├── diff@3.3.1
27 silly idealTree ├── dtrace-provider@0.2.8
27 silly idealTree ├── emitter-component@1.0.0
27 silly idealTree ├── escape-string-regexp@1.0.5
27 silly idealTree ├── eslint-plugin-node@5.2.0
27 silly idealTree ├── extend@1.2.1
27 silly idealTree ├── formidable@1.0.14
27 silly idealTree ├── fs.realpath@1.0.0
27 silly idealTree ├── glob@6.0.4
27 silly idealTree ├── growl@1.10.2
27 silly idealTree ├── has-flag@2.0.0
27 silly idealTree ├── he@1.1.1
27 silly idealTree ├── ignore@3.3.5
27 silly idealTree ├── inflight@1.0.6
27 silly idealTree ├── inherits@2.0.3
27 silly idealTree ├── methods@0.0.1
27 silly idealTree ├── mime@1.2.5
27 silly idealTree ├── minimatch@3.0.4
27 silly idealTree ├── minimist@0.0.8
27 silly idealTree ├── mkdirp@0.5.1
27 silly idealTree ├─┬ mocha@4.0.0
27 silly idealTree │ ├── commander@2.11.0
27 silly idealTree │ ├── debug@3.1.0
27 silly idealTree │ └── glob@7.1.2
27 silly idealTree ├── ms@2.0.0
27 silly idealTree ├── mv@2.1.1
27 silly idealTree ├── nan@1.0.0
27 silly idealTree ├── ncp@2.0.0
27 silly idealTree ├─┬ node-expat@2.1.4
27 silly idealTree │ └── nan@0.6.0
27 silly idealTree ├── node-ssdp@0.2.2
27 silly idealTree ├── once@1.4.0
27 silly idealTree ├── optimist@0.6.1
27 silly idealTree ├── options@0.0.6
27 silly idealTree ├── path-is-absolute@1.0.1
27 silly idealTree ├── path-parse@1.0.5
27 silly idealTree ├── qs@0.6.5
27 silly idealTree ├── reduce-component@1.0.1
27 silly idealTree ├── require-dir@0.1.0
27 silly idealTree ├── resolve@1.4.0
27 silly idealTree ├── rimraf@2.4.5
27 silly idealTree ├── semver@5.3.0
27 silly idealTree ├── should-equal@2.0.0
27 silly idealTree ├── should-format@3.0.3
27 silly idealTree ├── should-type-adaptors@1.0.1
27 silly idealTree ├── should-type@1.4.0
27 silly idealTree ├── should-util@1.0.0
27 silly idealTree ├── should@13.1.0
27 silly idealTree ├── superagent@0.17.0
27 silly idealTree ├── supports-color@4.4.0
27 silly idealTree ├── tinycolor@0.0.1
27 silly idealTree ├── to-array@0.1.4
27 silly idealTree ├── url-join@0.0.1
27 silly idealTree ├── wordwrap@0.0.3
27 silly idealTree ├── wrappy@1.0.2
27 silly idealTree ├── ws@0.4.32
27 silly idealTree └── xml2json@0.4.0
28 silly install generateActionsToTake
29 silly diffTrees action count 3
30 silly diffTrees add nan@0.6.0
31 silly diffTrees add node-expat@2.1.4
32 silly diffTrees add xml2json@0.4.0
33 silly decomposeActions action count 24
34 silly decomposeActions fetch nan@0.6.0
35 silly decomposeActions extract nan@0.6.0
36 silly decomposeActions preinstall nan@0.6.0
37 silly decomposeActions build nan@0.6.0
38 silly decomposeActions install nan@0.6.0
39 silly decomposeActions postinstall nan@0.6.0
40 silly decomposeActions finalize nan@0.6.0
41 silly decomposeActions refresh-package-json nan@0.6.0
42 silly decomposeActions fetch node-expat@2.1.4
43 silly decomposeActions extract node-expat@2.1.4
44 silly decomposeActions preinstall node-expat@2.1.4
45 silly decomposeActions build node-expat@2.1.4
46 silly decomposeActions install node-expat@2.1.4
47 silly decomposeActions postinstall node-expat@2.1.4
48 silly decomposeActions finalize node-expat@2.1.4
49 silly decomposeActions refresh-package-json node-expat@2.1.4
50 silly decomposeActions fetch xml2json@0.4.0
51 silly decomposeActions extract xml2json@0.4.0
52 silly decomposeActions preinstall xml2json@0.4.0
53 silly decomposeActions build xml2json@0.4.0
54 silly decomposeActions install xml2json@0.4.0
55 silly decomposeActions postinstall xml2json@0.4.0
56 silly decomposeActions finalize xml2json@0.4.0
57 silly decomposeActions refresh-package-json xml2json@0.4.0
58 silly install executeActions
59 silly doSerial global-install 24
60 verbose correctMkdir /home/parker/.npm/_locks correctMkdir not in flight; initializing
61 verbose lock using /home/parker/.npm/_locks/staging-3cbd895e2dbe2fb7.lock for /home/parker/build/nodecast/node_modules/.staging
62 silly doParallel extract 24
63 silly extract nan@0.6.0
64 silly pacote trying nan@https://registry.npmjs.org/nan/-/nan-0.6.0.tgz by hash: sha1-pU6+WXF7Rnx3QlMCvXwXV0yIeqo=
65 silly extract node-expat@2.1.4
66 silly pacote trying node-expat@https://registry.npmjs.org/node-expat/-/node-expat-2.1.4.tgz by hash: sha1-5VqCJJtxr7zgn/qIBwXsN1U8USE=
67 silly extract xml2json@0.4.0
68 silly pacote trying xml2json@https://registry.npmjs.org/xml2json/-/xml2json-0.4.0.tgz by hash: sha1-xeDRPGJw4adVfKowcfL6yLTR2E4=
69 silly pacote nan@https://registry.npmjs.org/nan/-/nan-0.6.0.tgz extracted to /home/parker/build/nodecast/node_modules/.staging/nan-8ba40321 by content address 27ms
70 silly pacote xml2json@https://registry.npmjs.org/xml2json/-/xml2json-0.4.0.tgz extracted to /home/parker/build/nodecast/node_modules/.staging/xml2json-4c35f921 by content address 29ms
71 silly pacote node-expat@https://registry.npmjs.org/node-expat/-/node-expat-2.1.4.tgz extracted to /home/parker/build/nodecast/node_modules/.staging/node-expat-c0166dc1 by content address 80ms
72 silly doReverseSerial unbuild 24
73 silly doSerial remove 24
74 silly doSerial move 24
75 silly doSerial finalize 24
76 silly finalize /home/parker/build/nodecast/node_modules/node-expat/node_modules/nan
77 silly finalize /home/parker/build/nodecast/node_modules/node-expat
78 silly finalize /home/parker/build/nodecast/node_modules/xml2json
79 silly doParallel refresh-package-json 24
80 silly refresh-package-json /home/parker/build/nodecast/node_modules/node-expat/node_modules/nan
81 silly refresh-package-json /home/parker/build/nodecast/node_modules/node-expat
82 silly refresh-package-json /home/parker/build/nodecast/node_modules/xml2json
83 silly doParallel preinstall 24
84 silly preinstall nan@0.6.0
85 info lifecycle nan@0.6.0~preinstall: nan@0.6.0
86 silly preinstall node-expat@2.1.4
87 info lifecycle node-expat@2.1.4~preinstall: node-expat@2.1.4
88 silly preinstall xml2json@0.4.0
89 info lifecycle xml2json@0.4.0~preinstall: xml2json@0.4.0
90 silly doSerial build 24
91 silly build nan@0.6.0
92 info linkStuff nan@0.6.0
93 silly linkStuff nan@0.6.0 has /home/parker/build/nodecast/node_modules/node-expat/node_modules as its parent node_modules
94 verbose linkBins nan@0.6.0
95 verbose linkMans nan@0.6.0
96 silly build node-expat@2.1.4
97 info linkStuff node-expat@2.1.4
98 silly linkStuff node-expat@2.1.4 has /home/parker/build/nodecast/node_modules as its parent node_modules
99 verbose linkBins node-expat@2.1.4
100 verbose linkMans node-expat@2.1.4
101 silly build xml2json@0.4.0
102 info linkStuff xml2json@0.4.0
103 silly linkStuff xml2json@0.4.0 has /home/parker/build/nodecast/node_modules as its parent node_modules
104 verbose linkBins xml2json@0.4.0
105 verbose linkBins [ { xml2json: 'bin/xml2json' },
105 verbose linkBins   '/home/parker/build/nodecast/node_modules/.bin',
105 verbose linkBins   false ]
106 verbose linkMans xml2json@0.4.0
107 silly doSerial global-link 24
108 silly doParallel update-linked 24
109 silly doSerial install 24
110 silly install nan@0.6.0
111 info lifecycle nan@0.6.0~install: nan@0.6.0
112 silly install node-expat@2.1.4
113 info lifecycle node-expat@2.1.4~install: node-expat@2.1.4
114 verbose lifecycle node-expat@2.1.4~install: unsafe-perm in lifecycle true
115 verbose lifecycle node-expat@2.1.4~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/parker/build/nodecast/node_modules/node-expat/node_modules/.bin:/home/parker/build/nodecast/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/ros/kinetic/bin:/home/parker/bin
116 verbose lifecycle node-expat@2.1.4~install: CWD: /home/parker/build/nodecast/node_modules/node-expat
117 silly lifecycle node-expat@2.1.4~install: Args: [ '-c', 'node-gyp rebuild' ]
118 silly lifecycle node-expat@2.1.4~install: Returned: code: 1  signal: null
119 info lifecycle node-expat@2.1.4~install: Failed to exec install script
120 verbose unlock done using /home/parker/.npm/_locks/staging-3cbd895e2dbe2fb7.lock for /home/parker/build/nodecast/node_modules/.staging
121 warn eslint-plugin-node@5.2.0 requires a peer of eslint@>=3.1.0 but none is installed. You must install peer dependencies yourself.
122 warn nodecast@0.0.10 No license field.
123 verbose stack Error: node-expat@2.1.4 install: `node-gyp rebuild`
123 verbose stack Exit status 1
123 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
123 verbose stack     at emitTwo (events.js:125:13)
123 verbose stack     at EventEmitter.emit (events.js:213:7)
123 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
123 verbose stack     at emitTwo (events.js:125:13)
123 verbose stack     at ChildProcess.emit (events.js:213:7)
123 verbose stack     at maybeClose (internal/child_process.js:927:16)
123 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
124 verbose pkgid node-expat@2.1.4
125 verbose cwd /home/parker/build/nodecast
126 verbose Linux 4.13.0-rc6-g311fc65c9fb9
127 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
128 verbose node v8.6.0
129 verbose npm  v5.4.2
130 error code ELIFECYCLE
131 error errno 1
132 error node-expat@2.1.4 install: `node-gyp rebuild`
132 error Exit status 1
133 error Failed at the node-expat@2.1.4 install script.
133 error This is probably not a problem with npm. There is likely additional logging output above.
134 verbose exit [ 1, true ]
````
