### ISSUE TITLE
ERROR: Could not locate the bindings file

### ISSUE THREAD

**Issue by matthewbschneider** [astro/node-expat#170]
Getting the following error on Debian 3.16.7 GNU/Linux

Error: Could not locate the bindings file. Tried:
 → /node_modules/node-expat/build/node_expat.node
 → /node_modules/node-expat/build/Debug/node_expat.node
 → /node_modules/node-expat/build/Release/node_expat.node
 → /node_modules/node-expat/out/Debug/node_expat.node
 → /node_modules/node-expat/Debug/node_expat.node
 → /node_modules/node-expat/out/Release/node_expat.node
 → /node_modules/node-expat/Release/node_expat.node
 → /node_modules/node-expat/build/default/node_expat.node
 → /node_modules/node-expat/compiled/4.4.5/linux/x64/node_expat.node
    at bindings (/node_modules/node-expat/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/node_modules/node-expat/lib/node-expat.js:4:32)

**Comment by matthewbschneider** [comment]
@astro any idea on a fix here?

**Comment by astro** [comment]
`find . -name node_expat.node`

**Comment by matthewbschneider** [comment]
@astro 

$ find . -name node_expat.node
./node_modules/node-expat/build/Release/node_expat.node
./node_modules/node-expat/build/Release/obj.target/node_expat.node

**Comment by astro** [comment]
looks alright?

**Comment by BradZzz** [comment]
I am also seeing this error when uploading to Heroku. Would be interested to know how to fix instead of trying a new library

**Comment by gupshuprenuka** [comment]
I am also facing this issue on Lambda

**Comment by UncleGus** [comment]
To fix this, I went into the node-expat folder in my node_modules folder, then I ran a node-gyp rebuild there. At first it complained about my npm_config_node_gyp variable, which was pointing at the node-gyp package folder itself, so I amended it to point at the bin\\node-gyp.js file itself. Like this:
`export npm_config_node_gyp=C:\\ProgramData\\nvm\\v8.13.0\\node_modules\\npm\\node_modules\\node_modules\\node-gyp\\bin\\node-gyp.js`

**Comment by azjgard** [comment]
For anyone from Google that come across this issue and is using Webpack:

I encountered this error when trying to deploy some code using the Serverless framework to a Lambda on AWS; the error was being thrown when Webpack was attempting to bundle everything.

I discovered that the problem stemmed from Webpack's inability to bundle native modules. I was able to fix it with two steps: 

1. Including the below in my `webpack.config.js` to tell Webpack that `node-expat` is an external module that shouldn't be bundled:
```
module.exports = {
  ...
  externals: ["node-expat"],
};
```

2. Including the below in my `serverless.yml` to tell Serverless that `node-expat` should be packaged into the `node_modules` included in the deployed .zip file:
```
custom:
  webpack:
    includeModules:
      forceInclude:
        - node-expat
```

Replace step 2 with whatever is necessary to make sure that `node_modules/node-expat` is available to your Node process at runtime, since it won't be in the bundle that Webpack spits out.
