### ISSUE TITLE
NODE_MODULE_VERSION error

### ISSUE THREAD

**Issue by pamarti** [astro/node-expat#185]
/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

node-expat : 2.3.16
node: 8.10
npm: 5.6
electron: 1.8.4

I also used electron-rebuild to build the package to new target node version
I also used node-gyp to rebuild node-expat. Nothing helped.

Any ideas to fix this issue?

**Comment by 8BitJonny** [comment]
Same Issue here

**Comment by drmrbrewer** [comment]
Same here.  Any solution to this?  It occurred after I upgrade from `node 8.12.0` to `node 10.13.0`.  I am using `node-expat` via [xml2json](https://www.npmjs.com/package/xml2json).  The error I get is when I run my node app:

	/root/workspace/myapp/node_modules/bindings/bindings.js:88
			throw e
			^

	Error: The module '/root/workspace/myapp/node_modules/node-expat/build/Release/node_expat.node'
	was compiled against a different Node.js version using
	NODE_MODULE_VERSION 64. This version of Node.js requires
	NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
	the module (for instance, using `npm rebuild` or `npm install`).
		at Object.Module._extensions..node (module.js:682:18)
		at Module.load (module.js:566:32)
		at tryModuleLoad (module.js:506:12)
		at Function.Module._load (module.js:498:3)
		at Module.require (module.js:597:17)
		at require (internal/module.js:11:18)
		at bindings (/root/workspace/myapp/node_modules/bindings/bindings.js:81:44)
		at Object.<anonymous> (/root/workspace/myapp/node_modules/node-expat/lib/node-expat.js:4:32)
		at Module._compile (module.js:653:30)
		at Object.Module._extensions..js (module.js:664:10)

**Comment by lfuelling** [comment]
I have the same problem. I tried building on 8.x, 10.x and 11.x. I am also using node-expat only as dependency of `xml2json`.

``` 
Error: The module 'node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (node_modules/node-expat/lib/node-expat.js:4:32)
```

**Comment by Sashlyn** [comment]
Has anyone found a solution to this outside of electron?
I've got the exact same issue as the OP but running on an Ubuntu server.

**Comment by hefc2016** [comment]
I have same error with node-expat.

<Error: The module '/home/hefc/GIT/xviz/examples/converters/kitti/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).>

Could anyone who fixed this issue share the solution ouside elelctron?

**Comment by sriramtorvi** [comment]
I had the same issue
Downgrading the node version from v12.18 to v10.21 and running npm rebuild helped me.

**Comment by miklcct** [comment]
same issue here

**Comment by miklcct** [comment]
Running npm rebuild helped me, but what is the equivalent on yarn?

**Comment by rubnogueira** [comment]
node-expat dependency is shipping a node_expat.node file tied to a specific Node version. This needs to be compiled on the fly when the user installs the dependencies.

For now we are doing this. Save this as scripts/fix-expat.js:
```js
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

try {
  console.log('[fix-expat] locating node-expat...');

  // 1. Find the path (using the command that worked for you)
  const output = execSync('pnpm list -r node-expat --parseable --depth=1', { 
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'] 
  });

  const foundPaths = output
    .split('\n')
    .filter(line => line && line.trim().endsWith('node-expat'));

  if (foundPaths.length === 0) {
    console.log('[fix-expat] No paths found.');
    process.exit(0);
  }

  foundPaths.forEach(symlinkPath => {
    try {
      // 2. Resolve the real path
      const realPath = fs.realpathSync(symlinkPath);
      console.log(`[fix-expat] Target: ${realPath}`);

      const buildDir = path.join(realPath, 'build');
      
      // 3. Clean existing build
      if (fs.existsSync(buildDir)) {
        console.log(`[fix-expat] Cleaning build dir...`);
        fs.rmSync(buildDir, { recursive: true, force: true });
      }

      // 4. FORCE BUILD IN PLACE
      // We explicitly call node-gyp rebuild inside that directory.
      // We use 'npx' to ensure we use a compatible node-gyp version.
      console.log(`[fix-expat] Compiling binary... (this may take a moment)`);
      
      execSync('npx node-gyp rebuild', { 
        cwd: realPath,   // <--- Important: run INSIDE the package folder
        stdio: 'inherit' // <--- Show us the compiler output/errors
      });
      
      console.log(`[fix-expat] Compilation successful for: ${realPath}`);

    } catch (err) {
      console.error(`[fix-expat] Build FAILED for ${symlinkPath}`);
      console.error(err.message);
      // Don't exit here, try other paths if any
    }
  });

  console.log(`[fix-expat] All done.`);

} catch (error) {
  console.error('[fix-expat] Critical Error:', error.message);
  process.exit(1);
}
```

and add this postinstall hook:
```
"postinstall": "node scripts/fix-expat.js"
```

This script is used with pnpm + workspaces but you can easily adapt for your package manager / use case. Ideally this should be solved in this codebase. cc @xmppo

**Comment by rubnogueira** [comment]
For anyone with this issue, this was solved in the PR #235.

<img width="1296" height="909" alt="Image" src="https://github.com/user-attachments/assets/43d65276-9fe4-4f2b-8878-3478c347ae73" />
