### ISSUE TITLE
How to solve 'ERR_DLOPEN_FAILED' with node_expat.node: Exec format error

### ISSUE THREAD

**Issue by julisch94** [astro/node-expat#218]
I have a project which uses the library `xml-stream` which again uses `node-expact` under the hood. And when building a docker image with this Dockerfile:
```
FROM node:16.16-alpine3.16

WORKDIR /app

RUN chown node:node /app

USER node:node

COPY --chown=node:node . .

RUN npm install

CMD ["npm", "start"]
```

and then starting the container I get the following error:
```
> my-api@0.0.1 start
> NODE_ENV=production node ./src/app.js

/app/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Error loading shared library /app/node_modules/node-expat/build/Release/node_expat.node: Exec format error
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/app/node_modules/node-expat/lib/node-expat.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```.

I am posting this issue because I found the fix for the issue and want to share the solution to save your time.

**Comment by julisch94** [comment]
The reason for this was that my full `node_modules` folder was added to the container including the dependency `node-expat` built for a **wrong architecture**. So what I had to do was **ignore** `node_modules` in Docker.

`.dockerignore`:
```
node_modules
```

### Even better solution
Copy `package.json` independently from the rest of your code. That way you split up the _install dependency_ and the actual application.

`Dockerfile`:
```
FROM node:16.16-alpine3.16

WORKDIR /app

RUN chown node:node /app

USER node:node

COPY --chown=node:node ["package.json", "package-lock.json*", "./"]

RUN npm install --production

COPY --chown=node:node  . .

CMD ["npm", "start"]
```
